### ISSUE TITLE
Friend Profile Modal

### ISSUE THREAD

**Issue by MRlolface249** [SE310-1/W.A.K#80]
## User Story

As a user,
I want to view my friends profile,
So that I can see details about the movies they watch.

## Additional Context

When viewing your friends list, on clicking one of your friends names, a modal will pop up  showing details about that user
Details include:

- Users Name
- Users Profile Picture 
- Users Top Favourite movie
- Link to full list of users favourite movies

## Dependency Management

Issue is dependent on #81 due to the lack of a profile picture being created.
All tasks which this dependency effects are tagged with #81 

Issue is dependent on #53 due to the current lack of ability to order the favourites list, this means that until this issue is closed we are unable to test task 7, additionaly task 4 will not function as intended but due to the current default behavouir of returning the top list (returns the first movie in the list) this task can still be tested and completed without this issue being closed, but will not display the full functionality till it is. 
All tasks which this dependency effects are tagged with #53 

## Acceptance Criteria

- [x] On clicking a user, a modal window appears
- [x] Modal window contains users Name
- [x] Modal window contains users Profile Picture #81 
- [x] Modal window contains users Top Favourite Movie #53 
- [x] A button for accessing users favourite movies is displayed
- [x] When clicked button will take you to the favourites page of the user
- [x] Favourites page will have rearranging disabled #53 
- [x] Favourites page will have a title to reflect that it is a different users list, and will display that users name
