### ISSUE TITLE
Friend UI Improvements

### ISSUE THREAD

**Issue by MRlolface249** [SE310-1/W.A.K#81]
## User Story

As a User,
I want to have a nice clean friends list page,
So that it's aesthetically pleasing and easier to navigate.

## Additional Context

Fix up the UI and styling of the friends list to make it more aesthetically pleasing and to keep it consistent with the rest of the website, this consistency will help with user navigation.

## Dependency Management

Issue #80  is dependent on this issue and tasks which need to be completed before implementation for #80  can begin 
are annotated in the acceptance criteria section by including a "( #80 )" at the end. 

This issue is dependent on #53, due to issue 5, however due to the default behavior of getting the top movie (by taking the first movie in the favorites list), and the fact that all tasks other than the ordering are complete, implementation can proceed. This issue will still be able to be tested but will not produce the desired outcome till #53 is complete.
All tasks which this dependency effects are tagged #53 

## Acceptance Criteria

- [x] Friend list is more aesthetically pleasing.
- [x] Styling is consistent with rest of website.
- [x] Users own profile picture (pfp) is displayed.
- [x] On clicking the profile picture you are presented with the option to upload an image to become the new pfp. #80 
- [x] Profile picture deafults to the image of the movie poster for the users top favourite movie. #53 #80 
- [x] Profile picture defaults to a random image of a movies poster if favourites list is empty. #80

**Comment by samcordner** [comment]
Closed by #90
